### ISSUE TITLE
模型推理cpu占用高，gpu几乎不占用

### ISSUE THREAD

**Issue by MisakaMikoto-o** [DanJun6737/TransFace#11]
大佬你好，我在调用这个模型推理的时候，发现cpu占用很高，但是gpu占用却几乎不升高，但是加载模型后显存占用确实变高了，至少是用到了显卡的，不知道是不是加载模型的时候没有完全加载到显卡中，调用和推理代码不是完全用的给出的demo，我把人脸检测和对齐部分用其他方法实现了，能帮我看看代码吗，谢谢

**Comment by MisakaMikoto-o** [comment]
`import onnxruntime
import torch
from typing import Mapping
import numpy as np

def collate_fn(data, device):
    """Prepare the input just before the forward function.
    This method will move the tensors to the right device.
    Usually this method does not need to be overridden.

    Args:
        data: The data out of the dataloader.
        device: The device to move data to.

    Returns: The processed data.

    """
    from torch.utils.data.dataloader import default_collate

    def get_class_name(obj):
        return obj.__class__.__name__

    if isinstance(data, dict) or isinstance(data, Mapping):
        # add compatibility for img_metas for mmlab models
        return type(data)({
            k: collate_fn(v, device) if k != 'img_metas' else v
            for k, v in data.items()
        })
    elif isinstance(data, (tuple, list)):
        if 0 == len(data):
            return torch.Tensor([])
        if isinstance(data[0], (int, float)):
            return default_collate(data).to(device)
        else:
            return type(data)(collate_fn(v, device) for v in data)
    elif isinstance(data, np.ndarray):
        if data.dtype.type is np.str_:
            return data
        else:
            return collate_fn(torch.from_numpy(data), device)
    elif isinstance(data, torch.Tensor):
        return data.to(device)
    elif isinstance(data, (bytes, str, int, float, bool, type(None))):
        return data
    elif get_class_name(data) == 'InputFeatures':
        # modelscope.preprocessors.nlp.InputFeatures
        return data
    elif get_class_name(data) == 'DataContainer':
        # mmcv.parallel.DataContainer
        return data
    else:
        raise ValueError(f'Unsupported data type {type(data)}')

def load_onnx_model(onnx_path):
    sess = onnxruntime.InferenceSession(
        onnx_path,
        providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
    out_node_name = []
    input_node_name = []
    for node in sess.get_outputs():
        out_node_name.append(node.name)

    for node in sess.get_inputs():
        input_node_name.append(node.name)

    return sess, input_node_name, out_node_name`

**Comment by MisakaMikoto-o** [comment]
```
sess, input_node_name, out_node_name = load_onnx_model("/home/BTFace-vit/models/cv_vit_face-recognition/model.onnx")
```

**Comment by MisakaMikoto-o** [comment]
https://colab.research.google.com/drive/1GYDmLzLvkhg6qwJul-2wwiLv4mWczVxQ?usp=sharing

**Comment by MisakaMikoto-o** [comment]
这个不能直接运行，缺少的人脸检测模型和人脸分割对齐库如果您需要的话我可以发给您

**Comment by DanJun6737** [comment]
Hi~@MisakaMikoto-o

我简单看了一下，听您这描述 “调用和推理代码不是完全用的给出的demo，我把人脸检测和对齐部分用其他方法实现了”，有可能是这里出了问题，怀疑是跟TransFace那块不兼容。TransFace整个框架是基于InsightFace实现的，如果你想改人脸检测和对齐部分，最好基于InsightFace来改吧，这样可能会避免这些bug。

**Comment by MisakaMikoto-o** [comment]
嗯，找到原因了，是onnxruntime-gpu版本和cudnn版本不兼容导致的，已修复

**Comment by DanJun6737** [comment]
> 嗯，找到原因了，是onnxruntime-gpu版本和cudnn版本不兼容导致的，已修复

嗯嗯，解决了就好！
