### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by Cassieyy** [DanJun6737/TransFace#2]
Thank you for your excellent work! 
I would like to finetune the network based on the pre-trained weights. Could you please provide them like "work_dirs/glint360k_vit_l/glint360k_model_TransFace_L.pt" you've mentioned?
Thanks in advance.

**Comment by DanJun6737** [comment]
Hi @Cassieyy ~

All pre-trained models can be found and downloaded in the section "TransFace Pretrained Models", (i.e., https://github.com/DanJun6737/TransFace#transface-pretrained-models). 

"glint360k_model_TransFace_L.pt" represents our TransFace-L model trained on the Glint360K dataset. 

You just need to create the "work_dirs/glint360k_vit_l/" directory and put the downloaded model into it.  

If you find it helpful for you, please cite our paper.

**Comment by Cassieyy** [comment]
ohhh, I've found it!!
It’s so kind of u, and thank you very much!!!
