### ISSUE TITLE
Inference questions

### ISSUE THREAD

**Issue by HeChengHui** [DanJun6737/TransFace#3]
@DanJun6737  thank you for your work.

I would like to ask the following:
1. for inferencing on own images, can i use this [file](https://github.com/DanJun6737/TransFace/blob/main/inference.py)?
2. if i am using this through modelscope, how do i specify certain models?

**Comment by DanJun6737** [comment]
@HeChengHui Thank you for your attention to our work.

1）Yes, of course, you can use this [file](https://github.com/DanJun6737/TransFace/blob/main/inference.py) to perform inference on your own face images. We have updated this inference file. You simply need to specify the size of the TransFace model and load the corresponding version of the pre-trained model to perform inference.

2）The current version of Modelscope only supports inference for the TransFace-B model trained on the Glint360K dataset. We will load other versions of the TransFace model onto the Modelscope platform as soon as possible. 
If you want to use our model now, you can download various versions of the pre-trained models we provide and load them for usage (i.e., https://github.com/DanJun6737/TransFace#transface-pretrained-models).

**Comment by HeChengHui** [comment]
@DanJun6737 
Thanks for the update!
