### ISSUE TITLE
when inference a image ,parameters about num_classes

### ISSUE THREAD

**Issue by yjdqk** [DanJun6737/TransFace#5]
why the file named  __init__.py  in backbone,all vit model's num_classes is setted the same as num_features?

**Comment by DanJun6737** [comment]
Hi @yjdqk ! 

In fact, the value of variable **num_classes** in file **init.py** represents the dimension of the features extracted by the Transformer Encoder，so it is equivalent to the value of variable **num_features**.

If you wish to set the number of classes for the classification head, we recommend modifying the value of variable **config.num_classes** in the [configs](https://github.com/DanJun6737/TransFace/blob/main/configs/), which will correspond to the **num_classes** in the [Partial FC file](https://github.com/DanJun6737/TransFace/blob/main/partial_fc_exp.py).

**Comment by yjdqk** [comment]
ok, thanks for your reply
