### ISSUE TITLE
Vit-L config

### ISSUE THREAD

**Issue by TranThanh96** [DanJun6737/TransFace#7]
Can you provide VitL config to train glint360k?

**Comment by DanJun6737** [comment]
Of course！ We will upload the corresponding configuration files in the next few days.

**Comment by DanJun6737** [comment]
Hi~ @TranThanh96 
We have uploaded the relevant configuration file.

**Comment by TranThanh96** [comment]
@DanJun6737  can you provide your training log? my loss is a little bit high

**Comment by DanJun6737** [comment]
Hi @TranThanh96 ~
Sorry, some training logs have been lost. Both the DPAP strategy and the EHSM strategy can cause the loss of the model to be higher in the early stages of training compared to a normal ViT model, but it will quickly decrease over time. Additionally, our configuration files are based on 8 V100 GPUs, so if a different number of GPUs is used, the corresponding configuration parameters need to be adjusted accordingly.
